import { BadRequestError } from "../../common/errors/errors";
import { generateReviewByAI } from "../ai/ai.service";
import {
  deleteReviewDAO,
  getAllReviewsDAO,
  getReviewByIdDAO,
  saveReviewDAO,
} from "./analysis.dao";
import { GenerateReviewInput, ReviewResponse } from "./analysis.types";

/**
 * @name generateReviewService
 * @description Generates a review using AI analysis and saves the result.
 */
export const generateReviewService = async ({
  resume,
  selfDescription,
  jobDescription,
  userId,
}: GenerateReviewInput): Promise<ReviewResponse> => {
  if (!resume || !selfDescription || !jobDescription) {
    throw new BadRequestError("All fields are required");
  }

  const reviewByAI = await generateReviewByAI({
    resume,
    selfDescription,
    jobDescription,
  });

  const data = await saveReviewDAO({
    resume,
    selfDescription,
    jobDescription,
    reviewByAI,
    userId,
  });

  return data as unknown as ReviewResponse;
};

/**
 * @name getAllReviewsService
 * @description Retrieves all reviews generated by a user.
 */
export const getAllReviewsService = async ({
  userId,
}: {
  userId: string;
}): Promise<ReviewResponse[]> => {
  const reviews = await getAllReviewsDAO({ userId });
  return reviews as unknown as ReviewResponse[];
};

/**
 * @name getReviewByIdService
 * @description Retrieves a single review by id and userId.
 */
export const getReviewByIdService = async ({
  reviewId,
  userId,
}: {
  reviewId: string;
  userId: string;
}): Promise<ReviewResponse | null> => {
  const review = await getReviewByIdDAO({ reviewId, userId });
  return review as unknown as ReviewResponse | null;
};

/**
 * @name deleteReviewService
 * @description Deletes a review by id and userId.
 */
export const deleteReviewService = async ({
  reviewId,
  userId,
}: {
  reviewId: string;
  userId: string;
}): Promise<any> => {
  return await deleteReviewDAO({ reviewId, userId });
};
