import { prisma } from "../../config/db.config";
import { Severity } from "@prisma/client";

/**
 * @name saveReviewDAO
 * @description Saves a review to the database.
 */
export const saveReviewDAO = async ({
  resume,
  selfDescription,
  jobDescription,
  reviewByAI,
  userId,
}: {
  resume: string;
  selfDescription: string;
  jobDescription: string;
  reviewByAI: any;
  userId: string;
}) => {
  return await prisma.review.create({
    data: {
      userId,
      resume,
      selfDescription,
      jobDescription,
      title: reviewByAI.title,
      matchScore: reviewByAI.matchScore,
      technicalQuestions: {
        create: reviewByAI.technicalQuestions,
      },
      behavioralQuestions: {
        create: reviewByAI.behavioralQuestions,
      },
      skillGaps: {
        create: reviewByAI.skillGaps,
      },
      preparationPlans: {
        create: reviewByAI.preparationPlan,
      },
    },
    include: {
      technicalQuestions: true,
      behavioralQuestions: true,
      skillGaps: true,
      preparationPlans: true,
      user: {
        select: {
          id: true,
          userName: true,
          email: true,
        },
      },
    },
  });
};

/**
 * @name getAllReviewsDAO
 * @description Retrieves all reviews generated by a user.
 */
export const getAllReviewsDAO = async ({ userId }: { userId: string }) => {
  return await prisma.review.findMany({
    where: {
      userId,
    },
    include: {
      technicalQuestions: true,
      behavioralQuestions: true,
      skillGaps: true,
      preparationPlans: true,
      user: {
        select: {
          id: true,
          userName: true,
          email: true,
        },
      },
    },
    orderBy: {
      createdAt: "desc",
    },
    take: 25,
  });
};

/**
 * @name getReviewByIdDAO
 * @description Retrieves a single review by id and userId.
 */
export const getReviewByIdDAO = async ({
  reviewId,
  userId,
}: {
  reviewId: string;
  userId: string;
}) => {
  return await prisma.review.findUnique({
    where: {
      id: reviewId,
      userId,
    },
    include: {
      technicalQuestions: true,
      behavioralQuestions: true,
      skillGaps: true,
      preparationPlans: true,
      user: {
        select: {
          id: true,
          userName: true,
          email: true,
        },
      },
    },
  });
};

/**
 * @name deleteReviewDAO
 * @description Deletes a review by id and userId.
 */
export const deleteReviewDAO = async ({
  reviewId,
  userId,
}: {
  reviewId: string;
  userId: string;
}) => {
  return await prisma.review.delete({
    where: {
      id: reviewId,
      userId,
    },
  });
};
